name: Using action in github
on: [push]
jobs:
  running-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: list files
        run: |
          pwd
          ls -a
      - name: checkout
        uses: actions/checkout@v3.0.2
      - name: list files after checkout
        run: |
          pwd
          ls -a
      - name: simple js action
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: srini
      - name: log greeting time
        run: echo "${{steps.greet.outputs.time}}"