name: shell commands
on: [push]
jobs:
  running_shell_command:
    runs-on: ubuntu-latest
    steps:
      - name: signle script
        run: echo "Welcome to github actions"
      - name: multi script
        run: |
         npm -v
         node -v
          

